# GÃ©nÃ©ration : `flutter gen-l10n` (ou build / hot reload utilisent les ARB).
# Source unique : franÃ§ais (app_fr.arb).
arb-dir: lib/l10n
template-arb-file: app_fr.arb
output-localization-file: app_localizations.dart



