// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_hs_XTxovKaTPz4SQ8cYGSlGmjue3JqY',
    appId: '1:738203717325:web:28a7a4da987d1caa36e384',
    messagingSenderId: '738203717325',
    projectId: 'paychek-trading',
    authDomain: 'paychek-trading.firebaseapp.com',
    storageBucket: 'paychek-trading.firebasestorage.app',
    measurementId: 'G-7HJGLQKN8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsNtrvdvIYEub-XTMNWD0YFU0VqLzRxuk',
    appId: '1:738203717325:android:da54e7c83f0bdc5336e384',
    messagingSenderId: '738203717325',
    projectId: 'paychek-trading',
    storageBucket: 'paychek-trading.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlCvFR5JKsu5Cfn9BQL_GoJ-Mk6TAkoAQ',
    appId: '1:738203717325:ios:9edfd96bbb7d41b136e384',
    messagingSenderId: '738203717325',
    projectId: 'paychek-trading',
    storageBucket: 'paychek-trading.firebasestorage.app',
    iosBundleId: 'pro.paychek.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlCvFR5JKsu5Cfn9BQL_GoJ-Mk6TAkoAQ',
    appId: '1:738203717325:ios:9edfd96bbb7d41b136e384',
    messagingSenderId: '738203717325',
    projectId: 'paychek-trading',
    storageBucket: 'paychek-trading.firebasestorage.app',
    iosBundleId: 'pro.paychek.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_hs_XTxovKaTPz4SQ8cYGSlGmjue3JqY',
    appId: '1:738203717325:web:db0bae4978e21fe836e384',
    messagingSenderId: '738203717325',
    projectId: 'paychek-trading',
    authDomain: 'paychek-trading.firebaseapp.com',
    storageBucket: 'paychek-trading.firebasestorage.app',
    measurementId: 'G-STKWTTFKKM',
  );
}
